steps:
#1. First Clone the Github Repo Containing the Server Profile change made aaah
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'echo'
  args: ['Pulling the Server Profile from github']
  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','${_SERVER_PROFILE_GIT_REPOSITORY}']
  

#2. Pull the Desired PingDirectory Docker image from Dockerhub 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'echo'
  args: ['Pulling the PingDirectory Docker image from Dockerhub']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']

#3. Pull the Desired PingDirectory Docker image from Dockerhub and retags the image using the server profile tag number
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'echo'
  args: ['Retagging the PingDirectory Docker image']
  
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}'
  - '${_GCR_REPOSITORY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}'

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'echo'
  args: ['Pushing the Docker image to GCR']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_GCR_REPOSITORY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}']
  
# #Update the container image using kubectl set newww
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - 'set'
#   - 'image'
#   - 'deployment/${_DEPLOYMENTNAME}'
#   - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: learn-gcp-with-mahesh
    _ZONE: asia-south1-a
    _GKE_CLUSTER: learn-gcp-with-mahesh-gke-cluster
    
    # #Repository Specific configuration. DevOps can change this settings
    # _DEPLOYMENTNAME: hello-world-service
    # _CONTAINERNAME: hello-world-service    
    # _REPO_NAME: cicd-service
    
    # Developers ONLY change
    _VERSION: v1.0

    
    # DESIRED PingDirectory Docker Image Configurations
    _PINGDIRECTORY_DOCKER_IMAGE_TAG: 9.2.0.0-alpine_3.17.2-al11-edge
    

    # GCR CONTAINER IMAGE REPOSITORY
    _GCR_REPOSITORY_URL: us-central1-docker.pkg.dev/pingdirectory-358917/likeminds-docker-repository
    


    # ServerProfile Repository Specific Variables
    _SERVER_PROFILE_GIT_REPOSITORY: https://github.com/TuanLikeminds/cicd-service
    _SERVER
