steps:


#1. Pull the Server Profile from Github
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','${_SERVER_PROFILE_GIT_REPOSITORY}','/shared']
  volumes:
  - name: cloud-build-ping
    path: /shared
  id: "Cloning the PingDirectory Server Profile git Repo"

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'ls'
  volumes:
  - name: cloud-build-ping
    path: /shared
  id: "Listing the contents of the Pulled Repository"


#2. Pull the Desired PingDirectory Docker image from Dockerhub 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'echo'
  args: ['Pulling the PingDirectory Docker image from Dockerhub']
  volumes:
  - name: cloud-build-ping
    path: /shared
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']

#
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['run','-d', '--name', 'pd-temp-container','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']
  
#   volumes:
#   - name: cloud-build-ping
#     path: /shared

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['run','-d', '--name', 'pd-temp-container','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']
  
#   volumes:
#   - name: cloud-build-ping
#     path: /shared
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','-d', '--name', 'pd-temp-container','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']
  id: "running the temp container and creating the serverprofile directory"
  volumes:
  - name: cloud-build-ping
    path: /shared




- name: 'gcr.io/cloud-builders/docker'
  args: ['cp','/shared/pingdirectory/.', 'pd-temp-container:/tmp/server-profile']
  volumes:
  - name: cloud-build-ping
    path: /shared

- name: 'gcr.io/cloud-builders/docker'
  args: ['commit', 'pd-temp-container', '${_GCR_REPOSITORY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_GCR_REPOSITORY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}']




substitutions:
     
    # DESIRED PingDirectory Docker Image Configurations
    _PINGDIRECTORY_DOCKER_IMAGE_TAG: 9.2.0.0-alpine_3.17.2-al11-edge
    

    # GCR CONTAINER IMAGE REPOSITORY
    _GCR_REPOSITORY_URL: us-central1-docker.pkg.dev/pingdirectory-358917/likeminds-docker-repository
    


    # ServerProfile Repository Specific Variables
    _SERVER_PROFILE_GIT_REPOSITORY: https://github.com/TuanLikeminds/gcp-server-profile
    _SERVER_PROFILE_RELEASE_TAG: V1.0.32

options:
    substitution_option: 'ALLOW_LOOSE'
