steps:


#2. Pull the Desired PingDirectory Docker image from Dockerhub 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'echo'
  args: ['Pulling the PingDirectory Docker image from Dockerhub']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']

#2. Pull THe git repository 


#3. Pull the Server Profile


  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','${_SERVER_PROFILE_GIT_REPOSITORY}','/shared']
  volumes:
  - name: cloud-build-ping
    path: /shared
  volumeMounts:
  - name: cloud-build-ping
    mountPath: /shared