steps:


#1. Pull the Server Profile from Github
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--branch', '${_SERVER_PROFILE_RELEASE_TAG}', '${_SERVER_PROFILE_GIT_REPOSITORY}', '/shared']
  volumes:
  - name: cloud-build-ping
    path: /shared
  id: "Cloning the PingDirectory Server Profile git Repo"

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'ls'
  volumes:
  - name: cloud-build-ping
    path: /shared
  id: "Listing the contents of the Pulled Repository"


#2. Pull the Desired PingDirectory Docker image from Dockerhub 
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']
  id: "Pull the Desired PingDirectory Docker image from Dockerhub"
 
 #3. Running the PingDirectory image in a Temp Container

- name: 'gcr.io/cloud-builders/docker'
  args: ['run','-d', '--name', 'pd-temp-container','pingidentity/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}']
  id: "Running the PingDirectory image in a Temp Container"
  volumes:
  - name: cloud-build-ping
    path: /shared

#4. Copying the Server profile from /shared/pingdirectory/. to pd-temp-container:/opt/in/

- name: 'gcr.io/cloud-builders/docker'
  args: ['cp','/shared/pingdirectory/.', 'pd-temp-container:/opt/in/']
  volumes:
  - name: cloud-build-ping
    path: /shared
  id: "Copying the Server profile from /shared/pingdirectory/. to pd-temp-container:/opt/in/"

#5. Commit Changes to the Image running in the temp container

- name: 'gcr.io/cloud-builders/docker'
  args: ['commit', 'pd-temp-container', '${_ARTIFACT_REGISTRY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}']
  id : "Commit Changes to the Image running in the temp container"


#6. Push the customized image to the Artifact Registry 

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_ARTIFACT_REGISTRY_URL}/pingdirectory:${_PINGDIRECTORY_DOCKER_IMAGE_TAG}-${_SERVER_PROFILE_RELEASE_TAG}']
  id: "Pushing the customized image to the Artifact Registry"



substitutions:
     
    # DESIRED PingDirectory Docker Image Configurations
    _PINGDIRECTORY_DOCKER_IMAGE_TAG: 2303-9.2.0.0
    
    # GCR CONTAINER IMAGE REPOSITORY
    _ARTIFACT_REGISTRY_URL: us-central1-docker.pkg.dev/pingdirectory-358917/likeminds-docker-repository

    # ServerProfile Repository Specific Variables
    _SERVER_PROFILE_GIT_REPOSITORY: https://github.com/TuanLikeminds/gcp-server-profile
    _SERVER_PROFILE_RELEASE_TAG: V-1.0.17
  
options:
    substitution_option: 'ALLOW_LOOSE'